apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  NODE_ENV: production
  PORT: "3000"

  ADMIN_URL: http://admin-service:3007
  CLIENT_URL: http://client-service:3001
  EMAIL_URL: http://email-service:3008
  MESSAGING_URL: http://messaging-service:3006
  NOTIFICATIONS_URL: http://notifications-service:3005
  PAYMENTS_URL: http://payments-service:3004
  PROVIDER_URL: http://provider-service:3002
  VIDEO_URL: http://video-service:3003
  USER_URL: http://user-service:3010

  HOST_URL: staging.usupport.online
